# Generated by Django 2.2.2 on 2019-06-20 13:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField(blank=True, default='')),
                ('upload_date', models.DateField(default=django.utils.timezone.now)),
                ('publish', models.CharField(choices=[('PR', 'Private'), ('PU', 'Public')], default='PR', max_length=7)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_images', to='albums.Album')),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
